### ISSUE TITLE
nmgs_metapopulation_average for the full model

### ISSUE THREAD

**Issue by apascualgarcia** [microbiome/NMGS#7]
Dear @antagomir,

I was wondering if you figured out how to reconstruct the composition of the metacommunity for the full neutral model, as far as I can see in the R vignette this problem was not solved, you said:

> Metacommunity distribution for the full neutral model (q) - are the species indices directly comparable, or how to combine across MCMC samples?

And as far as I can see the current version of `nmgs_metapopulation_average` returns TODO. I guess it is needed that the NMGS script returns an indexed vector or so, are you planning to tackle this problem? 

Thanks in advance,

Alberto

**Comment by antagomir** [comment]
The R code is experimental, and has not been developed or maintained since 2015. The C implementation is the primary one. Afaik there are no plans to tackle the above-mentioned coding issue in the foreseeable future due to scarce resources - unless @chrisquince has further comments.

**Comment by apascualgarcia** [comment]
Dear Leo,

Thanks for the fast response. Although I opened an issue related to the R implementation the problem is not the R script but the output of the C script, which does not provide any indexing and the number of species is variable for the full model.

In the scripts for the output analysis you provided in Perl, the script `AverageM.pl` sorts the vectors before the means are computed, so it averages abundances for species having the same rank. I may be missing something but I can't see why this is a solution since species with similar values may have different ranks across simulations.

This is also related to Figure 2 in the paper. You reported that, for the Panama trees, pN > pL so I would expect you representing in the NMDS-plot the metacommunities inferred with the full neutral model (this is not stated in the figure), so I can't see how a distance can be computed w.r.t the local samples with the current implementation of the code.

So perhaps there is something I do not fully understand but I would appreciate any help explaining how the metacommunity should be estimated for the full neutral model, in order to compare it with the local samples.

Thanks again,

Alberto

**Comment by chrisquince** [comment]
Hi Alberto,

I believe the C code does output probability vector samples from the metapopulation including an estimate of unobserved species as the S + 1th entry. This is equation 12 of the arxiv paper:

https://arxiv.org/pdf/1410.4038.pdf

The averaging over rank was just a quick way to try and represent the mean of those samples. For the NMDS I added the average metacommunity as a point using the average over samples. 

I have a Python implementation now that I could put in a repo. Would that be useful?

Thanks,
Chris

**Comment by apascualgarcia** [comment]
Hi Chris,

Thanks for the follow up. The output of the code gives a vector of S+1 entries for what you called the "local neutral model", but it has a variable number of entries for the "full neutral model". This is noted in the text of the paper when you refer to Eq. 12:

> Given this sample we can also generate a neutral metacommunity distribution, β̄^0_k , using Equation 12, since the ancestral frequencies T ·j = \sum_i=1 T ij are known. This will be a true neutral metacommunity since the
distribution will correspond to stick-breaking with parameter θ. **Note that the number of species observed can differ from S.**

Hence the metacommunity can easily be represented averaging over samples for the local metacommunity, as you said. But, for the full neutral model, performing the average would require indexing the species to establish the correspondence between them over samples (plus determining how the absence of data for some species is handled).

In my data, the local neutral model rejects neutrality but the full neutral model does not, so I could represent the local metacommunity but I think that an appropriate representation should consider the full model (perhaps is not that important because they may be similar after projecting them in the nmds axis). In summary, I  don't really need a code to perform the nmds, but just one that computes the average for the full model, or an indexing for the species so I can compute it myself. 

Thanks again for your help. 

Best,

Alberto

**Comment by chrisquince** [comment]
Hi Alberto,

There is a distinction between a sampled probability vector describing the metacommunity and a discrete sample from that. We represent the probability vector with S + 1 terms. If we generate discrete samples from it then we can have a variable number of species represented since we can observe new species. For comparisons to actual observed communities using that probability vector and comparing to relative proportions for each observed community with Bray-Curtis (setting the S+1th abundance to zero) would be fine. 

In the C code I think the file generated *_m.csv contains the metapopulation probability vector samples as the second row in each sample entry. The script AverageM.pl then averages those and I need to check but the first averaged vector outputted is the correct one.

One thing, there may be an error in the original paper (corrected in the latest arXiv) version where for testing neutrality we had the inequalities the wrong way round. I am not sure if this is the case for the perl script or not. I can check all that. I may shift everything into a new better documented repo with a Python version included over the next few months. It is nice to see people are interested in it.

Thanks,
Chris
